### register user
POST http://localhost:5000/api/auth/register
content-type: application/json

{   
    "name": "Kefilwe Sefara",
    "email": "kefilwewendy56@gmail.com",
    "password": "1234567"
}
### login user
POST http://localhost:5000/api/auth/login
content-type: application/json

{ 
    "email": "kefilwewendy56@gmail.com",
    "password": "1234567"
}

### Create Task
POST http://localhost:5000/api/task/create
content-type: application/json

{
    "option": "Personal" ,
    "name": "Kefilwe Sefara" ,
    "date": "04 December 2023" ,
    "time": "14:00"
    }

### Get All Tasks
GET  http://localhost:5000/api/task/all

### Get One Task
GET  http://localhost:5000/api/task/single/656f10eaff34c8515e526a62

### Update item by specific id 
PUT   http://localhost:5000/api/task/update/656f10eaff34c8515e526a62
content-type: application/json

{
    "option": "Work" ,
    "name": "Mpho" ,
    "date": "04 December 2023" ,
    "time": "14:00"
    }
### Delete by specific id 
DELETE    http://localhost:5000/api/task/delete/656f0609ff34c8515e526a16
